### PR TITLE
fix(links): weight links to substrate docs

### PR DESCRIPTION
**Pull request by TomaszWaszczyk**
I have fixed links to `weight` links to Substrate docs.

### CODE REVIEW

**Comment by andabak** [comment]
Thanks @TomaszWaszczyk . We are currently in a middle of a big PR (253) which will change structure of docs so this one will be considered when we merge that one.

**Review by andabak — CHANGES_REQUESTED** [review]
@TomaszWaszczyk please rebase to main branch. Big changes came after PR253 (new Build chapter)

**Comment by TomaszWaszczyk** [comment]
@andabak For sure I made the rebase badly, I am not able to find that links after those big changes, if will find them, will make PR with improved links.

For now, I closed PR and removed the branch.

**Comment by andabak** [comment]
OK. Thanks @TomaszWaszczyk !

**Pull request closed without merging**
