### PR TITLE
Feature/zkevm build japanese

### PR DESCRIPTION
**Pull request by Zac-eng**
I finished translating "learn/zkEVM/index.md" and "learn/zkEVM/faq.md" into Japanese.
Also I added img to the directory.
While editing the file, I noticed the app does not work by using path "/docs/learn/zkEVM/faq.md" in index.md.
So I changed to "/learn/zkEVM/faq.md".

### CODE REVIEW

**Review by Maar-io — CHANGES_REQUESTED** [review]
you should not change any of the existing english files. Please rebase

**Comment by andabak** [comment]
@Zac-eng only changes this PR should contain are the changes in the i18n/ja folder 

Perhaps the branch you worked in just got too stale.

Could you please remove all the files from this PR that are not in the i18n/ja folder. 

(including French etc)

**Comment by andabak** [comment]
@Zac-eng @meganskye @Maar-io 
I created a new branch and PR based only on top commits from this branch (and dropping all the conflicting ones)

Please check that PR and branch ( https://github.com/AstarNetwork/astar-docs/pull/522 branch https://github.com/AstarNetwork/astar-docs/tree/feat/add-japanese-1)

I think we should close this PR once we agree on the content of the new one

**Review by meganskye — APPROVED** [review]
looks good! thank you for the submission.

**Pull request closed without merging**
