### PR TITLE
Feature/landing page update

### PR DESCRIPTION
**Pull request by codespool**
Redesign the landing page according to design: https://www.figma.com/design/iWhh82EIXNR9EVSkc9sHAG/Astar-Docs?node-id=340-21&t=6nixgtL6wnmJAuwj-0

- customise header and footer
- implement custom search (swizzle the native algolia docusearch component)
- implement tab and dropdown menus

After CSS inconsistencies in the prod build:

- upgrade and lock all dependencies
- remove sass plugin
- modify build command so minifier is not breaking css
- fix case-insensitive links
- image and styles cleanup
- additional css updates:
  - consistent background color
  - background image
  - borders and small tweaks

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thanks!!

1. fix links

 > - Banner (homepage), (build & Earn) somehow button is not working.
 > - Banner faucet -> `https://docs.astar.network/docs/build/environment/faucet`
 
Screenshot 2024-07-26 at 14 35 24
Screenshot 2024-07-26 at 14 34 28
511-45c8-9feb-b85ae17df404">
-

2. Please remove old design banners
 > -  we just don't need them so no replacement but just remove them all from :https://github.com/AstarNetwork/astar-docs/tree/main/docs/build/img
  > -  but except this one - https://github.com/AstarNetwork/astar-docs/blob/main/docs/build/img/lockdropacc.png.

**Comment by Kahonnohak** [comment]
3. Footer

 > - Please adjust the padding for footer
 > - Please remove the background white and don't cut the gradients
 
Screenshot 2024-07-26 at 14 54 14

**Comment by Kahonnohak** [comment]
4. Mobile
 > - please make side margin 12px
 > - and change the padding inside of the box to 16px
 
Screenshot 2024-07-26 at 15 05 16

**Comment by Kahonnohak** [comment]
@codespool I have some request for a change, I would like to explain on Thursday together with other docs design. thank you!

**Review by bobo-k2 — APPROVED** [review]

**Pull request merged**
