### PR TITLE
Create All That Node

### PR DESCRIPTION
**Pull request by yunseonna**
Proposing to suggest the updated information for Free RPC endpoints powered by All That Node.

### CODE REVIEW

**Comment by meganskye** [comment]
i've made some adjustments but please add the images to this PR in the docs/build/integrations/node-providers/img folder so it will build correctly, thank you.

**Comment by yunseonna** [comment]
In the docs/build/integrations/node-providers/img folder, I clicked on "Add file" -> "Upload files," but it says "Uploads are disabled." Could you tell me how I can add images?

**Comment by gtg7784** [comment]
> In the docs/build/integrations/node-providers/img folder, I clicked on "Add file" -> "Upload files," but it says "Uploads are disabled." Could you tell me how I can add images?

You can upload the file from [your repo, patch-5 branch](https://github.com/yunseonna/astar-docs/tree/patch-5), it'll update to this PR

**Comment by meganskye** [comment]
hi [yunseonna](https://github.com/yunseonna) thanks again for the submission.

you're doing great so far 🙌

how about you email the images to me and i will add them here.  it's megan.skye@startale.com

**Comment by gtg7784** [comment]
Hi @yunseonna , Last week, I talked with Owen from All that node about this PR. He said will create new PR for this integration. So, I'll close this PR, Please create new PR for this documentation.
Thank you! 

cc. @fiexer @RHEEUNION

**Pull request closed without merging**
