### PR TITLE
zkEVM User Guides 2

### PR DESCRIPTION
**Pull request by Gunit2481**
- Add from Astar zkEVM to Astar EVM bridge
- Add from Astar zkEVM to Ethereum
- Add unstaking vASTR on Astar zkEVM
- Improve images
- Add JP translations

### CODE REVIEW

**Review by meganskye — COMMENTED** [review]
please confirm JP doc is complete & does not contain any duplicate info now that conflicts have been resolved.

**Comment by tksarah** [comment]
Good morning! I have checked these on staging. 

**Bridge-Ethereum**
It seems there are many mistakes in “**Bridge-Ethereum**”
It appears that significant corrections are necessary.
- Layerswap section has bug
- Relay Link section is duplicated
- insert a line break after ‘:::info'.

**Bridge-Astar-EVM:** 
Line 27
  Current  "### Astar EVMからAstar zkEVMへ"
  Update  "### Astar EVMからAstar zkEVMへ:"

**ASTR-Liquid-Staking:**
LGTM!

**Comment by tksarah** [comment]
I have checked again.

**Bridge-Ethereum**
Insert a line break after the word ‘info’ on line 68.

Current:

> :::info 転送は、Ethereum ネットワークの使用状況により、10 分から 30 分かかることがあります。

Update:

> :::info
> 転送は、Ethereum ネットワークの使用状況により、10 分から 30 分かかることがあります。


I’ve noticed an error in the original English version. It seems there is a “3.” in the Relay Link section.

スクリーンショット 2024-03-23 002918

Apart from these, it looks good to me (LGTM).

**Review by meganskye — APPROVED** [review]
awesome! lgtm!

**Pull request merged**
