### PR TITLE
Create mobile_wallet.md

### PR DESCRIPTION
**Pull request by andabak**
Adding translation for Indonesian for User Guide mobile_wallet.md

### CODE REVIEW

**Review by marvelet — COMMENTED** [review]
still need more works

**Comment by andabak** [comment]
@marvelet I will leave this PR open so when when mobile_wallet.md gets translated in Crowdin try to extend this PR with content of that file.

**Comment by andabak** [comment]
@marvelet any progress on this translation? any support needed

**Comment by marvelet** [comment]
Ivan,

I'm sorry, I totally forgot, I brought my laptop while I travel, I will do
that on this holiday

**Comment by fiexer** [comment]
Whats the status of this PR @marvelet ?
cc @andabak

**Comment by andabak** [comment]
This is not ready for review so converting to draft @marvelet

**Comment by andabak** [comment]
Will close this PR as is contains no substantial content.

**Pull request closed without merging**
